{% set name = "psy-reg" %}
{% set version = "1.1.0" %}
{% set sha256 = "76b28c6c7c36924f36762ddcfa57efec04246476f164797c658efca601bf8d44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - psyplot
  - psy-simple
  - statsmodels
  - scipy

test:
  imports:
  - psy_reg

about:
  home: https://github.com/Chilipp/psy-reg
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for visualizing and calculating regression plots

  description: |
    This psyplot plugin can be used to make fits to your data and visualize
    them
  doc_url: http://psyplot.readthedocs.io/projects/psy-reg
  dev_url: https://github.com/Chilipp/psy-reg

extra:
  recipe-maintainers:
    - Chilipp
