{% set name = "psy-reg" %}
{% set version = "1.5.0" %}
{% set sha256 = "c8003fe474a0a26330c0492b0e704e3956413813c8e25bb5cb538de40cdf49f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('psy-simple', max_pin='x.x') }}
    - statsmodels
    - scipy

test:
  imports:
    - psy_reg

about:
  home: https://github.com/psyplot/psy-reg
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Psyplot plugin for visualizing and calculating regression plots

  description: |
    This psyplot plugin can be used to make fits to your data and visualize
    them
  doc_url: http://psyplot.github.io/psy-reg
  dev_url: https://github.com/psyplot/psy-reg

extra:
  recipe-maintainers:
    - Chilipp
