{% set name = "psy-reg" %}
{% set version = "1.5.0" %}
{% set sha256 = "c8003fe474a0a26330c0492b0e704e3956413813c8e25bb5cb538de40cdf49f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - versioneer
    - tomli
  run:
    - python
    - {{ pin_compatible('psy-simple', max_pin='x.x', lower_bound='1.5.0') }}
    - statsmodels
    - scipy

test:
  imports:
    - psy_reg
    - psy_reg.plotters

about:
  home: https://github.com/psyplot/psy-reg
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSES/
  summary: Psyplot plugin for visualizing and calculating regression plots

  description: |
    This psyplot plugin can be used to make fits to your data and visualize
    them
  doc_url: http://psyplot.github.io/psy-reg
  dev_url: https://codebase.helmholtz.cloud/psyplot/psy-reg

extra:
  recipe-maintainers:
    - Chilipp
