travis:
  secure:
    BINSTAR_TOKEN: ZJgHLfbIBFP7Rkp5f7Rqh9BA2FOXmy2pZWgPvP+2qiyRKiuydaMufADEWG/WjxlbvnJ8ydPwP0K8v72e3wevqTFt7/REn5KXVnqsyZ6Z8AeDJabCdilbDoMNSbmd+GOH2YC9tUnh4D1c71vbIWq9zILqUdWjVIv8Pq2eR9BGl790nOyEu5doCTwB1WUoILGRgsFAKY1HC156xR5dBU6yj62Gsv3aiCTG6FM3hYlwVkoVfSTGfEHTvaFpr2Er0FhlbKYQ3y6sd3KC9H2K/LVaKcY3WQqVkQAVh0WKZvuamyjX1h4UOdP56B1R/fCDB57a0CuUE7GLes1POv0NpXKtGPj+eJ/dx/An4+qpznKPvR5y0HbWTL33wXDzWeEePlrxyWMUjYKkQEqAckEiM0I68Tv1HiaJwbkQoue5M3Sbqo3CHjVPz5w0ed/SsrDjm1qTP+pFm/o74S4nH1TeHf2HGRrER96lMkbp+KB9ZLebQeG3p/NgOglzZIUdkqvjCPSKzcW4/byuLRYixRXGj4WoIQG2vpczrvzomIwO6uqx44ec8aeF9nguSzKLhk0hHbrueNFns+MW6dCbT9kWDqFDs0VD6UoSoMISew9r1sD2P1S3n3Skh+LAzGLnbYPmhhjG6aA+041YbAwzmGL0PyapyAiJNC33XLggy4pElPu4qmI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
