appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ltfUOfSYnIuUiWM9Sg1hIuVFDQfU2o4P2pyDofnf377P1zTKNbmjc9Kj4dqU2iI/VXpgIOR+xDjjBQtuFwZPo//YiyIS+0ydiccTYOmTqgp8RE0T9IMGA5N3ZqHrADnQglu4abkdoUfoW0cxPhrogkbJu05HW6tDFblujpuBdmvhZzRuA9WRrery+am+WCWq3RWjKabPGvkc5tyV6IVjvnjmS9ieBxZLDTFvjfH2EUJAh9rbiYGeOHwiU0xqqT1t6jSfX2ZdbDp0yo7mvCYuzp9se9m1UwUUHoJOWK301K6avHLyd45r4mBQZGJltm2bJCBFSN0NmKcao2ThENED0g1iZ586rbENdod9v3kajvqZDx8hMAH8AXfzZNgril6FhQslUV4IScpAJBbY3iMgJOU+JRuCQYx9hbKMqNITYFfG2tRWKFNvdiVGIS1GTi5JA6VZIw8iZzV29bsWkl3NrWcm7LQhaH7p3m8dCoAS4LAzkIIEmTs5J2XnICLRaaBVjoYmQzFzZ9rbe/0Tttgnpu1O/td7DzPOE8mszynH0C5cmR7OCRmTLyQipNPJEFNZElTpGBlRrq8ljf7yWotxkQkFE2oGMK8UEEbUV5Uik7/VVsDLCAxtMLVYRdXOWaa83wN+yZ8bfEW91yLLiXqTzbFZRntbk1bpKGQNA3Yo1Co=}
